#!/bin/bash
#
# Makefile for RPM

TARGETS="aware perl-ZUtils-Common perl-ZUtils-Aware"
TOPDIR=`mktemp -d /tmp/make_${TARGET}_XXXXXX`
VERSION=`git tag -l 'v[0-9].[0-9]*' | sort -r | head -1`
RELEASE=`git rev-list HEAD | wc -l`
BRANCH=`git branch --no-abbrev | awk '{if ($1 == "*" ) { print $2 } }'`
HASH=`git rev-list --no-abbrev --max-count=1 --date-order --remove-empty --all`

printf "Targets:         %50s\n" $TARGETS
printf "Top Directory:   %50s\n" $TOPDIR
printf "Tag:             %50s\n" $VERSION
printf "Release:         %50s\n" $RELEASE
printf "Branch:          %50s\n" $BRANCH
printf "Hash:            %50s\n" $HASH

for TARGET in ${TARGETS}; do
    if [ ! -e RPMS/${TARGET}-${VERSION}-${RELEASE}.*.rpm ] ; then
        TBUILD=${TOPDIR}/$TARGET
        mkdir -p ${TBUILD}/BUILD ${TBUILD}/RPMS ${TBUILD}/SOURCES ${TBUILD}/SPECS ${TBUILD}/SRPMS ${TBUILD}/SCRATCH
        git archive --format=tar HEAD | tar -xf - -C ${TBUILD}
        sed -i 's/^Version:.*/Version:\t'${VERSION}'/g' ${TBUILD}/SPECS/${TARGET}.spec
        sed -i 's/^Release:.*/Release:\t'${RELEASE}'/g' ${TBUILD}/SPECS/${TARGET}.spec
        sed -i 's%^URL:.*%URL:\t'${BRANCH}'_'${VERSION}'-'${HASH}'%g' ${TBUILD}/SPECS/${TARGET}.spec
        git log --pretty=format:" * %at %cn %n - %s" | grep -v ^" --" | grep -v -- -- | awk '{ if ($1 == "*") { print " * " strftime("%a %b %d %Y",$2) " " $3 } else { print $0}}' >> ${TBUILD}/SPECS/${TARGET}.spec
        find ${TBUILD}/SRC/${TARGET} \( -name '.svn' -o -name '*~' \) -prune -o -not -type d -print > ${TBUILD}/SCRATCH/${TARGET}-${VERSION}.filelist
        tar -czf ${TBUILD}/SOURCES/${TARGET}-${VERSION}.tar.gz --no-recursion --transform='s,.*/SRC/,'${TARGET}'-'${VERSION}'/,' -T ${TBUILD}/SCRATCH/${TARGET}-${VERSION}.filelist
        rpmbuild -ba --define="_topdir ${TBUILD}" ${TBUILD}/SPECS/${TARGET}.spec
        mkdir -p SRPMS RPMS
        find ${TBUILD}/SRPMS -type f -exec mv {} SRPMS/. \;
        find ${TBUILD}/RPMS -type f -exec mv {} RPMS/. \;
    else 
        printf "Found existing RPMS:       %40s\n" `ls RPMS/${TARGET}-${VERSION}-${RELEASE}.*.rpm`
    fi
done
