#!/usr/bin/perl -w

my $major = 0;
my $minor = '$Revision: 575 $';
$minor =~ s/^.*: //g;
$minor =~ s/ \$$//g;

use ZUtils::Common;
use FindBin;
use POSIX;
use strict;

# -------------------------------------------------------------------
# Initialize Configuration Settings
# -------------------------------------------------------------------
my $cfgfile = $ENV{ZUTILS_CFGFILE} || "/etc/aware/aware.cfg";
load_config($cfgfile);
	

if ($#ARGV < 5) {

	print "Usage: $0 <host> <dba_user> <dba_pass> <user> <pass> <databaseName>\n";
	exit();
}
my $host = $ARGV[0];
my $dba_user = $ARGV[1];
my $dba_pass = $ARGV[2];
my $user = $ARGV[3];
my $pass = $ARGV[4];
my $dbname = $ARGV[5];

if (length($dba_pass) > 0) { $dba_pass = "-p$dba_pass"; }
chomp($dbname);

# -- update the existing schema
print " - Updating database: $dbname\n";
system("mysql -u $dba_user $dba_pass -h $host $dbname < $FindBin::Bin/update.sql");
